# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f62182e0e581ad85ccb1d94470daba8d0dfb9224e5dd4ce8d8668ee039cd23e6b1e9b4b810a3aefec9c2bcc01b0ba726f427924ec932c9239ecd21884fdddb29

test:
  secret_key_base: 4b0df10fbcc3467c88e325a51b30f11f3ffa4003ee48e024cf45285a6db38e0a000338ecefb6b9cc68224bb8a21c50dbd2751484faf04c04841eed1532081908

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
